## This code reads the box size from the CONTCAR file and applies strain to it and also outputs strained POSCAR files in respective folders.

In [8]:
import numpy as np
import os

# Read the initial box size from the input file
with open('CONTCAR', 'r') as f:
    lines = f.readlines()
box = np.array([list(map(float, line.split())) for line in lines[2:5]])

# Define the range of strains to apply
strain_range = np.linspace(-0.08, 0.08, num=25)

# Loop over the strain range and apply box scaling
for i, strain in enumerate(strain_range):
    # Calculate the new volume after applying the strain
    V1 = np.linalg.det(box) * (1 + strain)

    # Calculate the new length of each box vector
    L1 = V1**(1/3)

    # Calculate the scaling factor for each box vector
    s = L1 / np.linalg.norm(box, axis=0)

    # Apply the scaling factor to each box vector
    box_new = s[:, np.newaxis] * box.T

    # Create a new directory for each strain if it doesn't exist
    dirname = f"{i+1}-strained_{strain:.3f}"
    if not os.path.exists(dirname):
        os.makedirs(dirname)

    # Update the file with the new box size and strain value
    lines[0] = f"{strain:.3f}\n"
    lines[2:5] = [f"{box_new[i][0]} {box_new[i][1]} {box_new[i][2]}\n" for i in range(3)]
    with open(f'{dirname}/POSCAR', 'w') as f:
        f.writelines(lines)

    # Print the new box vectors and volume
    print("Strain = {:.2f}%".format(strain*100))
    print(box_new.T)
    print("Volume = {:.4f}".format(V1))


Strain = -8.00%
[[ 8.33037455e+00 -1.96919415e-02 -1.73387720e-02]
 [-1.98810174e-02  8.33038869e+00 -8.34792873e-03]
 [-1.71894223e-02 -8.20476360e-03  8.33039378e+00]]
Volume = 578.0961
Strain = -7.33%
[[ 8.35044782e+00 -1.97393921e-02 -1.73805524e-02]
 [-1.99289236e-02  8.35046200e+00 -8.36804429e-03]
 [-1.72308428e-02 -8.22453420e-03  8.35046710e+00]]
Volume = 582.2852
Strain = -6.67%
[[ 8.37042504e+00 -1.97866157e-02 -1.74221328e-02]
 [-1.99766007e-02  8.37043925e+00 -8.38806362e-03]
 [-1.72720650e-02 -8.24421019e-03  8.37044437e+00]]
Volume = 586.4743
Strain = -6.00%
[[ 8.39030736e+00 -1.98336150e-02 -1.74635157e-02]
 [-2.00240512e-02  8.39032161e+00 -8.40798783e-03]
 [-1.73130915e-02 -8.26379271e-03  8.39032673e+00]]
Volume = 590.6634
Strain = -5.33%
[[ 8.41009590e+00 -1.98803926e-02 -1.75047034e-02]
 [-2.00712779e-02  8.41011017e+00 -8.42781807e-03]
 [-1.73539244e-02 -8.28328286e-03  8.41011531e+00]]
Volume = 594.8526
Strain = -4.67%
[[ 8.42979174e+00 -1.99269510e-02 -1.7545698